### ISSUE TITLE
76561198798718992

### ISSUE THREAD

**Issue by sjiebn** [Surikkusu/Destiny2CheaterList#2]
作弊类型：无限复活、锁头
证据：[https://braytech.org/pgcr/8883124008](url)
![QQ图片20210725153430](https://user-images.githubusercontent.com/49134233/126891469-edd726d7-cd8b-4caa-8e28-7a5558302e36.png)

**Comment by Surikkusu** [comment]
有具体的视频或者战绩吗，这数据除了轮椅和雷神爆头率看着挺正常的

**Comment by sjiebn** [comment]
我当时就和他排到一起打混战了，无限复活，锁头，生涯800杀的人能打出这个爆头率说实话，我看不懂但是我大受震撼，怎么说我也是生涯10W+的，还不至于去骗人

>

**Comment by Surikkusu** [comment]
https://github.com/Surikkusu/Destiny2CheaterList/blob/main/Cheater%20List/76561198798718992
