### ISSUE TITLE
76561199025943168

### ISSUE THREAD

**Issue by A1ex-Mcaron** [Surikkusu/Destiny2CheaterList#4]
作弊类型：辅助瞄准
证据链接：https://destinytracker.com/destiny-2/profile/steam/4611686018500591990/
补充
![image](https://user-images.githubusercontent.com/40230026/126905028-8259c02a-1781-43f5-8373-1efa656e9424.png)
![image](https://user-images.githubusercontent.com/40230026/126905035-63ea0cdf-9ccb-4f06-973b-1f26189d9b94.png)
![image](https://user-images.githubusercontent.com/40230026/126905046-87379279-b8f1-4857-b1b3-9530e0816665.png)
![image](https://user-images.githubusercontent.com/40230026/126905064-9b8e00a6-9a94-4392-a0b7-a15b16657fbd.png)

**Comment by Surikkusu** [comment]
已经添加 https://github.com/Surikkusu/Destiny2CheaterList/blob/main/Cheater%20List/76561199025943168
进一步交流可以加一下[D2CL交流群](https://jq.qq.com/?_wv=1027&k=E0UG7axG)
