### ISSUE TITLE
76561199152149790

### ISSUE THREAD

**Issue by NorwaysForest** [Surikkusu/Destiny2CheaterList#5]
锁头透视

**Comment by Surikkusu** [comment]
![R5129~ILMHS4G_OCRI0A TL](https://user-images.githubusercontent.com/87602611/127342890-07983e7c-7b71-4795-ba0d-738bcbc237cb.png)
![518@_`@ASWY}O5`RU%F}~_L](https://user-images.githubusercontent.com/87602611/127342889-edc1908e-d630-4bf7-b8d3-4c1458920204.PNG)
![R5129~ILMHS4G_OCRI0A TL](https://user-images.githubusercontent.com/87602611/127342898-6141628d-2a6a-4329-9ba7-ef6732b5ac7e.png)

当前数据无法鉴定为作弊 请补充更多证据

**Comment by Surikkusu** [comment]
找到了 是个无限重弹
![1C%$FY19TW8}R FV9H_5)2E](https://user-images.githubusercontent.com/87602611/127343193-c36d7ae6-4915-4e4e-8173-ed4095cbc189.png)
建议下次提交的时候可以自己添加证据 有时候没仔细看会找不到作弊情况。。

**Comment by Surikkusu** [comment]
已添加https://github.com/Surikkusu/Destiny2CheaterList/blob/main/Cheater%20List/76561199152149790
